#!/bin/sh
set -eu

CONFIG_DIR="${HOME}/.GarminDb"
CONFIG_FILE="${CONFIG_DIR}/GarminConnectConfig.json"
PASSWORD_FILE="${CONFIG_DIR}/garmin_password.txt"
INTERVAL_MINUTES="${GARMIN_SYNC_INTERVAL_MINUTES:-60}"
BACKOFF_STEP_MINUTES="${GARMIN_BACKOFF_STEP_MINUTES:-15}"
MAX_BACKOFF_MINUTES="${GARMIN_MAX_BACKOFF_MINUTES:-360}"
LOG_FILE="/tmp/garmindb-sync.log"

mkdir -p "${CONFIG_DIR}"

python -m pip install --no-cache-dir garmindb

echo "Waiting for Garmin config generated by Health HQ..."
while [ ! -f "${CONFIG_FILE}" ] || [ ! -f "${PASSWORD_FILE}" ]; do
  sleep 15
done

run_sync() {
  mode="$1"
  rm -f "${LOG_FILE}"

  if [ "${mode}" = "initial" ]; then
    set +e
    garmindb_cli.py --all --download --import --analyze >"${LOG_FILE}" 2>&1
    code="$?"
    set -e
  else
    set +e
    garmindb_cli.py --all --download --import --analyze --latest >"${LOG_FILE}" 2>&1
    code="$?"
    set -e
  fi

  cat "${LOG_FILE}"

  if grep -qi "failed to login\|invalid username or password\|rate limited\|returned 429" "${LOG_FILE}"; then
    return 10
  fi

  return "${code}"
}

echo "Starting scheduled GarminDB sync every ${INTERVAL_MINUTES} minutes..."
delay_minutes="${INTERVAL_MINUTES}"
first_run=1

while true; do
  if [ "${first_run}" -eq 1 ]; then
    echo "Running initial GarminDB sync..."
    mode="initial"
    first_run=0
  else
    mode="latest"
  fi

  if run_sync "${mode}"; then
    delay_minutes="${INTERVAL_MINUTES}"
    echo "Garmin sync succeeded. Next run in ${delay_minutes} minutes."
  else
    step="${BACKOFF_STEP_MINUTES}"
    candidate="$((delay_minutes + step))"
    if [ "${candidate}" -gt "${MAX_BACKOFF_MINUTES}" ]; then
      delay_minutes="${MAX_BACKOFF_MINUTES}"
    else
      delay_minutes="${candidate}"
    fi
    echo "Garmin sync failed (likely auth/rate limit). Backing off to ${delay_minutes} minutes."
  fi

  sleep "$((delay_minutes * 60))"
done
